---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-test
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-test
    spec:
      containers:
      - name: flask-test
        image: alexdio77/flask-test
        ports:
        - name: http
          containerPort: 8000
