apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alexdio77/flask-test.git
    targetRevision: HEAD
    path: /
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-test
  syncPolicy:
    automated:
      prune: false
      selfHeal: false