apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-deploy
  labels:
    app: flask-test-app
  annotations:
spec:
  selector:
    matchLabels:
      app: flask-test-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
      - name: flask-test-app
        image: alexdio77/flask-test
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
